from google.cloud import bigquery
import re


client = bigquery.Client()


# Only datasets Gemini is allowed to query
ALLOWED_DATASETS = [
    "pulse_trade_semantic",
    "pulse_trade_ai"
]


# SQL commands that should never be generated
FORBIDDEN_KEYWORDS = [
    "INSERT",
    "UPDATE",
    "DELETE",
    "MERGE",
    "DROP",
    "ALTER",
    "CREATE",
    "TRUNCATE",
    "GRANT",
    "REVOKE"
]


MAX_BYTES_BILLED = 5 * 1024 * 1024 * 1024  # 5 GB


DEFAULT_LIMIT = 100



def validate_dataset_access(sql: str):
    """
    Ensures query uses only approved datasets.
    """

    for dataset in ALLOWED_DATASETS:
        if dataset in sql:
            return True

    return False



def validate_read_only(sql: str):
    """
    Allows only SELECT queries.
    """

    normalized_sql = sql.strip().upper()


    if not normalized_sql.startswith("SELECT"):
        return False


    for keyword in FORBIDDEN_KEYWORDS:

        if keyword in normalized_sql:
            return False


    return True



def add_limit(sql: str):
    """
    Prevents Gemini from returning huge datasets.
    """

    if "LIMIT" not in sql.upper():

        sql = sql.rstrip(";")

        sql += f"\nLIMIT {DEFAULT_LIMIT}"


    return sql



def execute_bigquery(sql: str):
    """
    Executes SQL generated by Gemini.

    Security layers:
    1. Dataset whitelist
    2. Read-only SQL validation
    3. Query size protection
    4. Row limit protection
    5. IAM enforced access
    """


    # Layer 1:
    # Dataset validation

    if not validate_dataset_access(sql):

        return {
            "error":
            "Query rejected. "
            "Only approved semantic datasets are allowed."
        }



    # Layer 2:
    # Read only validation

    if not validate_read_only(sql):

        return {
            "error":
            "Only SELECT queries are allowed."
        }



    # Layer 3:
    # Add row protection

    sql = add_limit(sql)



    try:

        job_config = bigquery.QueryJobConfig(
            maximum_bytes_billed=MAX_BYTES_BILLED
        )


        job = client.query(
            sql,
            job_config=job_config
        )


        result = job.result()


        rows = []


        for row in result:

            rows.append(dict(row))


        return rows



    except Exception as e:


        return {

            "error": str(e)

        }